pipeline:
  build:
    image: golang
    commands:
      - go get
      - go build
      - go test
  deploy-to-staging:
    image: golang
    when:
      branch: master
    commands:
      - echo "hello, world!"